### ISSUE TITLE
Export json file to Google Storage bucket

### ISSUE THREAD

**Issue by chernandezm1986** [redis/riot#163]
Hi,

I'm running a command in a Cloud Function on GCP to export a file and store it in a Google Storage bucket. The command I'm using is:

`riot-standalone-4.1.7-linux-x86_64/bin/riot file-export -h my-redis-ip -p 6379 -c --tls --cacert server_ca.pem --key-pattern mykey:* --gcs-project my-gcp-project gs://my-gcs/export_redis.json`
However, I encounter the following error:
```
Exporting   0% [                                        ] 0/323 (0:00:00 / ?) ?/s[main] ERROR org.springframework.batch.core.step.AbstractStep - Encountered an error executing step file-export-step in job file-export
java.lang.UnsupportedOperationException: gs://my-gcs/export_redis.json cannot be resolved to absolute file path
	at com.google.cloud.spring.storage.GoogleStorageResource.getFile(GoogleStorageResource.java:248)
	at org.springframework.batch.item.support.AbstractFileItemWriter.getOutputState(AbstractFileItemWriter.java:355)
	at org.springframework.batch.item.support.AbstractFileItemWriter.open(AbstractFileItemWriter.java:296)
	at org.springframework.batch.item.support.CompositeItemStream.open(CompositeItemStream.java:124)
	at org.springframework.batch.core.step.tasklet.TaskletStep.open(TaskletStep.java:292)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:226)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:153)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:418)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:132)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:317)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:148)
	at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:59)
	at com.redis.riot.core.AbstractJobCommand.execute(AbstractJobCommand.java:98)
	at com.redis.riot.AbstractExportCommand.execute(AbstractExportCommand.java:41)
	at com.redis.riot.core.AbstractCallableCommand.call(AbstractCallableCommand.java:24)
	at com.redis.riot.core.AbstractCallableCommand.call(AbstractCallableCommand.java:11)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at com.redis.riot.Riot.execute(Riot.java:98)
	at com.redis.riot.Riot.lambda$commandLine$0(Riot.java:31)
	at com.redis.riot.core.LoggingMixin.lambda$executionStrategy$0(LoggingMixin.java:113)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.redis.riot.core.MainCommand.run(MainCommand.java:36)
	at com.redis.riot.Riot.main(Riot.java:23)

Exporting   0% [                                        ] 0/323 (0:00:00 / ?) `?/s`
Job failed
```

I have confirmed that I have write access to Google Cloud Storage. When I run the export command to create the JSON file locally:

`riot-standalone-4.1.7-linux-x86_64/bin/riot file-export -h my-redis-ip -p 6379 -c --tls --cacert server_ca.pem --key-pattern mykey:* export_redis.json`
and then execute a copy command to Google Cloud Storage, the file uploads correctly.

Can you help me, please?

**Comment by jruaux** [comment]
There was a regression in 4.1.7. This should be fixed in the latest early-access release.
